### PR TITLE
Add Random LoRA Stack and Random Weight LoRA Nodes

### PR DESCRIPTION
**Pull request by scottmudge**
I added two new nodes. One is a "Random LoRA Stack", which randomly applies the 3 LoRAs in the stack. There are two main modes for this: `exclusive` mode, where only 1 of the 3 LoRAs in the stack is applied randomly, or non-exclusive mode, where they're all independently applied randomly based on the `chance` parameter.

The "Random Weight LoRA" is similar, but instead it is only a single LoRA where the weight is randomly adjusted with the defined min/max range.

Both of these nodes also have a "stride" parameter, which determines how many cycles need to go by before re-randomization occurs.

There's also a "force randomize" parameter which ensures the next randomization is always different from the previous, which is useful for the "Random LoRA Stack".

I had to get a bit creative with the way `IS_CHANGED` operates with the primary node method. Since I wanted to make sure each node is invoked every cycle, but to only have it return a "changed" state when a new randomization occurs, the randomization itself had to happen with `IS_CHANGED`, and so I had to store data about the state of each node in a static map. If you just have `IS_CHANGED` return "NaN" like other nodes to ensure the node is always refreshed every cycle, the LoRAs always get reloaded every cycle, even if they haven't changed. So this gets around that.

But it works, and the extra data being stored in the static map is minimal.

### CODE REVIEW

**Comment by scottmudge** [comment]
They don't have to go with random prompts. I actually keep my prompt the same, but I use a variety of stylistic LoRAs and if I'm not sure how I'd like to mix them or weight them, I use these nodes to randomize them. But it can definitely be used with random prompts do add even more stochastic behavior.

**Comment by rbfussell** [comment]
Did not Just a note on these, did not want to open an issue for a feature request since  I love the idea myself,  but would like to add my concern.   Randomly applying a LoRa would need to include keyword negotiation for the triggers for many LoRas ,   otherwise often you will see little effect from  the initial prompt.  

prompt_and_trigger_LoRa
prompt only_LoRa
prompt only_no_LoRa

There may need to be an options for further prompt inclusions,   for example  using yummyfood does not really do much unless you trigger it with the keyword,   you can see in the three example,  prompt only,  prompt with lora, and prompt lora and keyword,   workflow for each is embedded.  I think the easiest method would be and int 0-2 output for which lora is selected,  and that can be used to select from a list of three prompts in another node.  Though that means a small setup would be needed to implement it or have text boxes with each LoRa extra keywords and combine the conditioning internally as my setup shows externally, workflows should be embedded in images.

**Comment by scottmudge** [comment]
That's a good point. The style loras I've been using haven't required additional prompt keywords for enhancement, so it hasn't yet been an issue for me, but that kind of cross-node communication was a bit beyond me. The Random LoRA Weight node would be useful regardless, but I suppose for the Random LoRA Stack, not having that kind of dynamic prompt mutation to correspond with a chosen LoRA requiring a changed prompt would be a limitation.

**Comment by Suzie1** [comment]
i had a super busy week, so didn't get a chance to do the PR this weekend
do you just want me to merge the one node for the weights?

**Comment by Suzie1** [comment]
hi, i'm doing the merge now
i have been super busy this week because of starting a new job

**Comment by Suzie1** [comment]
thanks guys, i really appreciate your contribute
there are several people very excited to test this
sorry it took so long, Suzie

**Comment by rafstahelin** [comment]
Amazing thx!

thanks

best regards, raf

**Pull request merged**
